Hero/ update css
KlimovAnton/Team15-project pull request #11
Opened 2024-03-16 20:10 UTC by LesyaKot

2024-03-16 22:20 UTC, KlimovAnton requested changes
1 Змінити title (якщо ти робиш через br, то в тебе повинено бути два тайтла (два, томущо моб і табл однакові) коли юзер дивиться з мобілки чи табл показує тайл моб чи табл, а тайтл для десктопу знаходиться в хтмл з display:none, і навпоки)
Приклад: 
title {
@media screen and (min-width:768px) {
            display: none;
        }
}

2024-03-17 07:05 UTC, LesyaKot commented
пофіксила

2024-03-17 10:27 UTC, KlimovAnton requested changes
1 Підтяни мейн!

2024-03-17 11:02 UTC, LesyaKot commented
done

2024-03-17 11:17 UTC, KlimovAnton approved these changes
Добре

2024-03-17 11:17 UTC, merged