add html and base css
KlimovAnton/Team15-project pull request #2
Opened 2024-03-15 14:04 UTC by miroslavVakulenko

є html,  накидав базовий css. немає поки svg, слайдера кнопок та акордеону js

2024-03-15 18:01 UTC, KlimovAnton requested changes
1. Добав контейнер
2. Всі блоки в моб та табл прибиті до лівоі стінки (зроби флекси по середені)

2024-03-15 21:37 UTC, KlimovAnton requested changes
1 Допиши шрифти (sans-serif)
2 Закінчи з таблеткою та десктопом (html та css)

2024-03-15 22:24 UTC, miroslavVakulenko commented
кномки з технологіями не слухаються мене зовсім, порухай ul будь ласка

2024-03-16 23:42 UTC, KlimovAnton requested changes
1 Перед початком роботи обнови мейн!!!
2 ul кличуть list, li кличуть item. Якщо в тебе перший клас називаэться .about-me-head-list, то другий повинен називаться .about-me-head-item. Вложені родітельски класи завжди більше по назві.
3 Width ми не задаэмо ні в яких блоках, це все виравнюється родителем. 
4 Width у картинок задається обов'язкого в теге img у html
5 Перероби картинку з допомогою тега picture
Приклад:
<picture>
  <source srcset="
      ./images/team1.jpg 1x, 
      ./images/team1-2x.jpg 2x
      " media="(min-width:1200px)">
  <source srcset="
      ./images/team1tabl.jpg 1x, 
      ./images/team1tabl.jpg 2x
      " media="(min-width:768px)">
  <source srcset="
      ./images/team1-mob.jpg 1x, 
      ./images/team1-mob-2x.jpg 2x
      " media="(min-width:480px)">
  <img src="./images/team1.jpg" alt="person1" width="450" height="460">
</picture>
6 Треба добавити СВГ іконки

Перероби без Width і код запрацює адекватно

2024-03-17 10:06 UTC, KlimovAnton reviewed
Звичайно в тебе не працює картинке, друже. Я тобі скинув приклад, а не точний код я к ветеб повинно бути. 
Змени в ньому розміри екранів, путь к файлу, задай ширину та висоту по макету

2024-03-18 10:13 UTC, KlimovAnton approved these changes
Треба доробити картинки

2024-03-18 10:13 UTC, merged