Feature/cover js
KlimovAnton/Team15-project pull request #30
Opened 2024-03-18 23:02 UTC by IrinaPapulova

2024-03-19 01:24 UTC, KlimovAnton requested changes
1 Вже працює - це добре, але він якось дивно включається, коли починає рухатися здається що лагає
2 Я думаю що сет тайм аут можно прибрати. Коли вони разом починають наче краще виглядає

2024-03-20 02:47 UTC, IrinaPapulova commented
добавила ректангл 1 в розмітку (попередньо замінила її в папці img/desktop- бо була скачана з фоном)?прибрала медіа в html, підкоригувала css, прибрала сеттаймаут в  js але перестало працювати, свариться на свайпер- побороти не змогла

2024-03-20 06:31 UTC, KlimovAnton requested changes
щось я не бачу помилок свайперу, а кажеш що є

2024-03-20 09:55 UTC, IrinaPapulova commented
> щось я не бачу помилок свайперу, а кажеш що є

у мене в консолі видає помилку на секцію ревью, а в ній свайпер, він обмежує чи відключає скрол, я поки не знайшла як його побороти, але ще подумаю як обійти. в Інеті - є пропозиція про підключення бібліотеки Лодаш, але ще не вспіла розібратися.

2024-03-20 17:46 UTC, KlimovAnton approved these changes

2024-03-20 17:46 UTC, merged